### ISSUE TITLE
Inaccurate Results with ADX

### ISSUE THREAD

**Issue by Zouuup** [bukosabino/ta#21] opened 2018-09-25 17:39 UTC
Hi!

Thanks for TA! Great job! 
It seems that i'm getting inaccurate data with ADX, at least data is different compared to cryptowatch and other sources.
import krakenex
import ta
from pykrakenapi import KrakenAPI

```
api = krakenex.API()
k = KrakenAPI(api)
df, last = k.get_ohlc_data("XXBTZEUR", ascending=True, interval=5)
ohlc = ta.utils.dropna(df)
print(ta.trend.adx(ohlc.high, ohlc.low, ohlc.close))
```
and output is

```
...
2018-09-25 17:35:00    22.381099
Name: adx, Length: 720, dtype: float64
```
while to ADX on website is for same interval/lenght is 12.54

**Comment by bukosabino** [comment] 2018-09-25 22:35
Hi @Zouuup ,

ADX have more parameters. By default, with this function call you are using `n_period = 14`. 

Are you sure if cyptowatch or other webs use this same value for this parameter?

Regards.

**Comment by Zouuup** [comment] 2018-09-26 07:11
Thanks for the answer, yes all values including n period are the same.

**Comment by bukosabino** [comment] 2018-10-14 14:28
Hi @Zouuup ,

I am working in a new implementation to ADX indicator: https://github.com/bukosabino/ta/blob/master/dev/adx_test.ipynb

But, I need more time to solve this issue.

Regards,

**Comment by bukosabino** [comment] 2018-10-24 19:48
Hi @Zouuup ,

@innaky has fixed this issue. You can see his code in this pull request: https://github.com/bukosabino/ta/pull/30

So, if you want, you can update your library version (0.4.0) and check the new results.

Thanks to everyone!

**Comment by bizso09** [comment] 2018-10-26 22:31
This is giving NaNs on the example data

**Comment by bukosabino** [comment] 2018-10-27 07:45
fixed in 0.3.7 version

**Comment by scolemann** [comment] 2018-10-27 23:17
Hi,

I updated to 3.7 and noticed adx_pos, adx_neg, and adx_indicator were removed.  Was that intentional and will they be added back?

Thank you for all your work on this library!

**Comment by bukosabino** [comment] 2018-10-28 10:33
Hi @scolemann ,

Yes, it was intentional. I have fixed the indicator and I think is better use only the ADX indicator ('trend_adx').

If you need 'adx_pos' or 'adx_neg' I can add them.

Best,

**Comment by felipeleonardi** [comment] 2018-10-31 00:01
Hi,

I think it would be very useful if I had the 'adx_pos' and 'adx_neg', so I could see the intersections between the lines.

This lib is great, thank you !!!

**Comment by t3chap** [comment] 2018-11-05 01:15
I would like the adx_pos and the adx_neg as well.  I find them useful.  Thanks.

**Comment by Nideesh1** [comment] 2018-11-09 07:51
Hi I am getting an error running, DF = ta.trend.adx(high, low, close, n=14, fillna=False). 
I have high, low, close in pandas.Series with 14 entries each.

The error is: IndexError: index 14 is out of bounds for axis 0 with size 1

Is anyone else getting this error?

**Comment by rsandx** [comment] 2019-06-19 19:52
I'm using version 0.4.5, got all NaN outside of the initial value 0. This is caused by the following code:
    pdm = high.combine(cs, lambda x1, x2: get_min_max(x1, x2, 'max'))
    pdn = low.combine(cs, lambda x1, x2: get_min_max(x1, x2, 'min'))

But it works fine if not calling the get_min_max method:
    pdm = high.combine(cs, lambda x1, x2: max(x1, x2) if not np.isnan(x1) and not np.isnan(x2) else np.nan)
    pdn = low.combine(cs, lambda x1, x2: min(x1, x2) if not np.isnan(x1) and not np.isnan(x2) else np.nan)

You can test it with adx_test.ipynb.

**Comment by bukosabino** [comment] 2019-11-07 22:35
At this moment ADX implementation works like a charm.

In fact, I have implemented some ![tests](https://github.com/bukosabino/ta/blob/f0acf1a82027fd9bb6d822a1afc10e051ed36241/ta/tests/trend.py#L9) in the library based on the dataset provided by ![Stockcharts](http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx).

**Closed** 2019-11-07 22:36 UTC
Labels: bug
